# Copyright 2019 ProximaX Limited. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.

# we use java
language: java

# try build using both oracle and openjdk
jdk:
  - oraclejdk8
  - openjdk8

# cache maintenance for gradle builds to avoid upload of caches
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# prepare for build
before_install:
  - chmod -R ug+x travis

install:
  - travis/install.sh

# build and test the app
script:
  - ./gradlew build jacocoTestReport coveralls

# add publishing stage that publishes data out
jobs:
  include:
    - stage: push to master
      jdk: openjdk8
      if: type = push AND branch = master
      script:
        - echo "Publishing snapshot"
        - ./gradlew publishAllPublicationsToSnapshotRepository
        - echo "Publishing javadoc to pages"
        - travis/publish_javadoc.sh
    - stage: releasing tag
      jdk: openjdk8
      if: tag IS present
      script:
        - echo "Publishing release $TRAVIS_TAG to public repository"
        - ./gradlew publishAllPublicationsToReleaseRepository -Pversion=$TRAVIS_TAG
